// js/pdf-export.js — generate PDF report using jsPDF (loaded from CDN)
export async function exportReportPDF(resultData, childName) {
  // Load jsPDF dynamically
  if (!window.jspdf) {
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
  }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(28, 25, 23);
  doc.roundedRect(10, 10, W - 20, 38, 4, 4, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9); doc.setFont('helvetica','normal');
  doc.text('Ripa Elevate', 18, 22);
  doc.setFontSize(18); doc.setFont('helvetica','bold');
  doc.text(childName + ' — Assessment Report', 18, 33);
  doc.setFontSize(8); doc.setFont('helvetica','normal');
  doc.text(new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' }), 18, 42);
  y = 60;

  // Result overview
  doc.setTextColor(28, 25, 23);
  doc.setFontSize(13); doc.setFont('helvetica','bold');
  doc.text('Assessment Overview', 15, y); y += 8;

  const fields = [
    ['Category',     resultData.category],
    ['Level Reached',resultData.level_name + ' (' + resultData.level_reached + ')'],
    ['Score',        resultData.score_pct + '%'],
    ['Supports Used',resultData.supports_summary || 'None'],
  ];
  fields.forEach(([label, val]) => {
    doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor(100,100,100);
    doc.text(label + ':', 15, y);
    doc.setFont('helvetica','normal'); doc.setTextColor(28,25,23);
    doc.text(String(val), 55, y);
    y += 7;
  });
  y += 6;

  // Analysis
  doc.setFontSize(13); doc.setFont('helvetica','bold'); doc.setTextColor(28,25,23);
  doc.text('Analysis', 15, y); y += 8;
  doc.setFontSize(9); doc.setFont('helvetica','normal');
  const lines = doc.splitTextToSize(resultData.analysis || '', W - 30);
  doc.text(lines, 15, y); y += lines.length * 5 + 8;

  // Strengths
  if (resultData.strengths?.length) {
    doc.setFontSize(11); doc.setFont('helvetica','bold');
    doc.text('Strengths', 15, y); y += 7;
    resultData.strengths.forEach(s => {
      doc.setFontSize(9); doc.setFont('helvetica','normal');
      doc.text('• ' + s, 18, y); y += 6;
    });
    y += 4;
  }

  // Growth areas
  if (resultData.growth_areas?.length) {
    doc.setFontSize(11); doc.setFont('helvetica','bold');
    doc.text('Areas for Growth', 15, y); y += 7;
    resultData.growth_areas.forEach(g => {
      doc.setFontSize(9); doc.setFont('helvetica','normal');
      doc.text('• ' + g, 18, y); y += 6;
    });
  }

  // Footer
  doc.setFontSize(7); doc.setTextColor(150,150,150);
  doc.text('Generated by Ripa Elevate · ripaelevate.com · For personal and educational use only', 15, 285);

  doc.save(`ripa-elevate-report-${childName.replace(/\s+/g,'-').toLowerCase()}-${Date.now()}.pdf`);
}

function loadScript(src) {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) { resolve(); return; }
    const s = document.createElement('script');
    s.src = src; s.onload = resolve; s.onerror = reject;
    document.head.appendChild(s);
  });
}
